### ISSUE TITLE
Unhandled stream error in pipe

### ISSUE THREAD

**Issue by dan335** [okgrow/meteor-image-upload#19] opened 2016-02-16 06:41 UTC
I'm getting this error.

```
Error: ENOENT, open '/opt/cfs/files/_tempstore/userImages-MtfYynGvTEqEbx4Mq-0.chunk' 
throw er; // Unhandled stream error in pipe. 
stream.js:94 
```

Only happens in production.  Is this what https://github.com/okgrow/meteor-image-upload/pull/16 is referring to?

**Comment by pauldowman** [comment] 2016-03-01 15:21
@dan335 When does this occur? How frequently? #16 is what happens on startup if temp store chunks haven't been cleaned up and the filesystem gets cleared (e.g. on a PaaS hosting service where there's a new temporary filesystem on every restart or for every app container).

**Comment by benstr** [comment] 2016-04-11 20:07
Closing, cannot reproduce.

**Closed as completed by benstr** 2016-04-11 20:07 UTC
Labels: can't reproduce
